spring:
  application:
    name: employee-service
  config:
    import: "optional:configserver:http://localhost:8088"

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_employee
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update